---
spring.config.activate.on-profile: local

kakao:
  api:
    url: https://dapi.kakao.com
    restApiKey: cfbc099a0c16f83522e329e08aa94539

naver:
  api:
    url: https://openapi.naver.com
    client-id: 1C4V9j5UotOB5mNQ0BKA
    client-secret: 5zROow2LcY
